SOURCES = cannyedgedetect facedetector framework linedetection motiondetection opticalflow

OPENCV_DIR =	/home/ubuntu/Desktop/OpenCV-2.3.0/

CXX_FLAGS =   	-Wall -pthread -march=i686 -ffunction-sections  -O3 -DNDEBUG -DPYTHON_USE_NUMPY=1 \
		-fomit-frame-pointer -ffast-math -msse -msse2 -mfpmath=387 \
		-I/usr/lib/pymodules/python2.7/numpy/core/include \
		-I$(OPENCV_DIR). \
		-I$(OPENCV_DIR)release \
		-I$(OPENCV_DIR)include \
		-I$(OPENCV_DIR)include/opencv \
		-I$(OPENCV_DIR)modules/core/include \
		-I$(OPENCV_DIR)modules/flann/include \
		-I$(OPENCV_DIR)modules/imgproc/include \
		-I$(OPENCV_DIR)modules/video/include \
		-I$(OPENCV_DIR)modules/highgui/include \
		-I$(OPENCV_DIR)modules/ml/include \
		-I$(OPENCV_DIR)modules/calib3d/include \
		-I$(OPENCV_DIR)modules/features2d/include \
		-I$(OPENCV_DIR)modules/objdetect/include \
		-I$(OPENCV_DIR)modules/legacy/include \
		-I$(OPENCV_DIR)modules/contrib/include

LXX_FLAGS=	-Wall -pthread -march=i686 -ffunction-sections  -O3 -DNDEBUG  \
		-fomit-frame-pointer -ffast-math -msse -msse2 -mfpmath=387 \
		-rdynamic -ldl -lm -lpthread -lrt \
		$(OPENCV_DIR)release/lib/libopencv_core.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_flann.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_imgproc.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_highgui.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_ml.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_video.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_objdetect.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_features2d.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_calib3d.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_legacy.so.2.3.0 \
		$(OPENCV_DIR)release/lib/libopencv_contrib.so.2.3.0 \
		-ldl -lm -lpthread -lrt -lz -Wl,-rpath,$(OPENCV_DIR)release/lib 

all:
	g++ $(CXX_FLAGS) -o example.o -c example.cpp
	g++ example.o -o example $(LXX_FLAGS)

clean:
	rm *.o
	rm $(SOURCES)

